### ISSUE TITLE
Typo in readme needs to be fixed.

### ISSUE THREAD

**Issue by KumarManoj-S** [KumarManoj-S/contractpy#5]
In README file, there is a typo in the basic usage example

`      {
            'orderId': Types:INTEGER,
            'price': Types:FLOAT
        }`

Here `:` has been used instead of `.`
This needs to be changed as follows,

`      {
            'orderId': Types.INTEGER,
            'price': Types.FLOAT
        }`

**Comment by Maheejaiswal** [comment]
Hello  ,i am new here please assign it to me

**Comment by KumarManoj-S** [comment]
@Maheejaiswal Thanks for your contribution.
